name: Ruff
on:
  pull_request:
  push:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python w/ Poetry
        uses: actions/setup-python@v5
        with:
          cache: poetry

      - run: ruff check --output-format=github .
